import type { RhythmPresetId, RhythmProfile } from '../domain/types';

export const RHYTHM_PRESETS: Record<RhythmPresetId, RhythmProfile> = {
  'human-natural': {
    id: 'human-natural',
    label: '真人自然',
    description: '保留轻微犹豫、末端修正和舒适的动作间隔。',
    globalSpeed: 1,
    dragFrames: 22,
    pickupDelayFrames: 3,
    placementSettleFrames: 7,
    betweenActionFrames: 14,
    clearDelayFrames: 4,
    clearDurationFrames: 18,
    cameraRecoveryFrames: 13,
    easing: 'easeInOutCubic',
  },
  'tight-fast': {
    id: 'tight-fast',
    label: '紧凑快速',
    description: '缩短空拍与停顿，适合高密度试玩演示。',
    globalSpeed: 1.16,
    dragFrames: 14,
    pickupDelayFrames: 1,
    placementSettleFrames: 4,
    betweenActionFrames: 6,
    clearDelayFrames: 2,
    clearDurationFrames: 13,
    cameraRecoveryFrames: 8,
    easing: 'easeOutCubic',
  },
  'suspense-burst': {
    id: 'suspense-burst',
    label: '悬念爆发',
    description: '拖拽前段克制，关键落点与清除被有意放大。',
    globalSpeed: 0.94,
    dragFrames: 24,
    pickupDelayFrames: 4,
    placementSettleFrames: 8,
    betweenActionFrames: 16,
    clearDelayFrames: 6,
    clearDurationFrames: 25,
    cameraRecoveryFrames: 18,
    easing: 'easeOutBack',
  },
  'combo-rush': {
    id: 'combo-rush',
    label: '连击冲刺',
    description: '快速连续落子，清除之间仅保留最短呼吸。',
    globalSpeed: 1.28,
    dragFrames: 12,
    pickupDelayFrames: 1,
    placementSettleFrames: 3,
    betweenActionFrames: 4,
    clearDelayFrames: 1,
    clearDurationFrames: 11,
    cameraRecoveryFrames: 7,
    easing: 'easeOutCubic',
  },
};

export const RHYTHM_PRESET_LIST = Object.values(RHYTHM_PRESETS);
